### ISSUE TITLE
ValidateSet duplicated to all properties

### ISSUE THREAD

**Issue by janegilring** [worxspace/PSPulumi#3] opened 2022-06-22 15:23 UTC
Happens due to variable not being cleared in the module generation process

**Comment by rdbartram** [comment] 2022-06-24 20:28
resolved in #5 module version 0.0.3

this was caused by a based build session. we are looking to implement a build pipeline, with plenty of tests, so stay tuned

**Closed by rdbartram** 2022-06-24 20:28 UTC
